name: Dataflow Pipeline

on:
    push:
        branches:
            - main

    workflow_dispatch:

jobs:
    run-dataflow:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: 'auth'
          uses: 'google-github-actions/auth@v1'
          with:
            credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'

        - name: Set up Google Cloud SDK
          uses: google-github-actions/setup-gcloud@v1  

        - name: 'Use gcloud CLI'
          run: 'gcloud info'
            
        - name: Install deps
          run: |
            python -m pip install --upgrade pip
            pip install apache-beam[gcp]
        
        - name: Get Terraform Outputs
          id: terraform
          run: |
            terraform init
            terraform apply -auto-approve
            echo "RAW_LOGS_BUCKET_URL=$(terraform output -raw raw_logs_bucket)" >> $GITHUB_ENV


        - name: Run Dataflow Pipeline
          run: |
            # Ensure correct directory
            cd ${{ github.workspace }}/scripts/
            ls -al

            python dataflow.py \
            --runner DataflowRunner \
            --project ${{ secrets.GCP_PROJECT_ID }} \
            --temp_location ${{ env.RAW_LOGS_BUCKET_URL }}/*txt \
            --region us-central1